### PR TITLE
REPRO NEEDED: Random death upon login?

### PR DESCRIPTION
**Pull request by mockdot**
## Description

This is an attempt to fix the random scenario where you login and your character is dead. I have not been able to properly pin-point where it is being caused, after looking at some code and I guess plain guessing, I believe it might be related to the way that hunger and thirst are working. Is it possible that when playerDropped is executed we are not saving it properly and even if player is logged out it continues to go down on the server? If we look at logout, we are using it: https://github.com/Qbox-project/qbx-core/blob/8b159d595d275aa38e39efe6cd20fe8cf3f6d19c/server/player.lua#L163

Would love to see if more people can test and reproduce.

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by Manason** [comment]
If that's the case, wouldn't it mean the root cause of this bug is players who dropped aren't being properly removed from the player list that is using by the loop to drop hunger/thirst? Shouldn't we look there for the fix?

**Comment by mockdot** [comment]
You are completely right, I did not pay attention that the cron actually does have a player table, it's possible this isn't being properly deleted upon player dropped I guess? https://github.com/Qbox-project/qbx-core/blob/8b159d595d275aa38e39efe6cd20fe8cf3f6d19c/server/loops.lua#L1

**Comment by Manason** [comment]
> You are completely right, I did not pay attention that the cron actually does have a player table, it's possible this isn't being properly deleted upon player dropped I guess?
> 
> https://github.com/Qbox-project/qbx-core/blob/8b159d595d275aa38e39efe6cd20fe8cf3f6d19c/server/loops.lua#L1

Check where player is removed from QBCore.Players on drop event.

**Comment by mockdot** [comment]
Seems to be along here: https://github.com/Qbox-project/qbx-core/blob/8b159d595d275aa38e39efe6cd20fe8cf3f6d19c/server/events.lua#L37

**Comment by mockdot** [comment]
Doing some debugprint tests, it does appear to put it to nil when closing the game and the QBCore.Players table does not show that user anymore on cron execution... not sure if it's a race condition

**Comment by BerkieBb** [comment]
That indentation is a little off, unless it's just my phone

**Comment by mockdot** [comment]
I think this might have been fixed by the changes done with qbx-medical/qbx-hud.

**Pull request closed without merging**
