### PR TITLE
fix(server/player): fix licenses

### PR DESCRIPTION
**Pull request by mockdot**
## Description

- Adding id metadata for id_card on qbx-cityhall

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Review by Manason — APPROVED** [review]
Does the definition of PlayerEntity reflect this licenses table?

**Comment by mockdot** [comment]
> Does the definition of PlayerEntity reflect this licenses table?

Would you be able to guide me onto how could I verify this? Would definition be setting the param/return on top?

**Comment by Manason** [comment]
> > Does the definition of PlayerEntity reflect this licenses table?
> 
> Would you be able to guide me onto how could I verify this? Would definition be setting the param/return on top?

Check storage.lua for the PlayerEntity definition

**Comment by mockdot** [comment]
Done! Thank you

**Review by Manason — APPROVED** [review]

**Review by BerkieBb — APPROVED** [review]

**Pull request merged**
