### PR TITLE
compat(drawtext) compat with qb-core

### PR DESCRIPTION
**Pull request by legende11**
## Description

fix drawtext export for qb-core

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality. (nope, sorry)
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by Manason** [comment]
Is there a generalized solution for all exports, or must each export be added in two places in the future?

**Comment by BerkieBb** [comment]
> Is there a generalized solution for all exports, or must each export be added in two places in the future?

Just like that, two places

**Comment by ChatDisabled** [comment]
Unfortunately what we signed up for with a name change

**Comment by BerkieBb** [comment]
Hey! I didn't approve yet

**Comment by ChatDisabled** [comment]
lgtm, pack it and SHIP IT

**Pull request merged**
